<?php

return [
    'Gender' => [
        'Male',
        'Female',
        'Other',
        'Prefer not to say',
    ],

    'Country' => [
        'Afghanistan',
        'Albania',
        'Algeria',
        'Andorra',
        'Angola',
        'Antigua and Barbuda',
        'Argentina',
        'Armenia',
        'Australia',
        'Austria',
        'Azerbaijan',
        'Bahamas',
        'Bahrain',
        'Bangladesh',
        'Barbados',
        'Belarus',
        'Belgium',
        'Belize',
        'Benin',
        'Bhutan',
        'Bolivia',
        'Bosnia and Herzegovina',
        'Botswana',
        'Brazil',
        'Brunei',
        'Bulgaria',
        'Burkina Faso',
        'Burundi',
        'Cabo Verde',
        'Cambodia',
        'Cameroon',
        'Canada',
        'Central African Republic',
        'Chad',
        'Chile',
        'China',
        'Colombia',
        'Comoros',
        'Congo (Congo-Brazzaville)',
        'Costa Rica',
        'Croatia',
        'Cuba',
        'Cyprus',
        'Czechia (Czech Republic)',
        'Democratic Republic of the Congo',
        'Denmark',
        'Djibouti',
        'Dominica',
        'Dominican Republic',
        'Ecuador',
        'Egypt',
        'El Salvador',
        'Equatorial Guinea',
        'Eritrea',
        'Estonia',
        'Eswatini (fmr. "Swaziland")',
        'Ethiopia',
        'Fiji',
        'Finland',
        'France',
        'Gabon',
        'Gambia',
        'Georgia',
        'Germany',
        'Ghana',
        'Greece',
        'Grenada',
        'Guatemala',
        'Guinea',
        'Guinea-Bissau',
        'Guyana',
        'Haiti',
        'Holy See',
        'Honduras',
        'Hungary',
        'Iceland',
        'India',
        'Indonesia',
        'Iran',
        'Iraq',
        'Ireland',
        'Israel',
        'Italy',
        'Jamaica',
        'Japan',
        'Jordan',
        'Kazakhstan',
        'Kenya',
        'Kiribati',
        'Kuwait',
        'Kyrgyzstan',
        'Laos',
        'Latvia',
        'Lebanon',
        'Lesotho',
        'Liberia',
        'Libya',
        'Liechtenstein',
        'Lithuania',
        'Luxembourg',
        'Madagascar',
        'Malawi',
        'Malaysia',
        'Maldives',
        'Mali',
        'Malta',
        'Marshall Islands',
        'Mauritania',
        'Mauritius',
        'Mexico',
        'Micronesia',
        'Moldova',
        'Monaco',
        'Mongolia',
        'Montenegro',
        'Morocco',
        'Mozambique',
        'Myanmar (formerly Burma)',
        'Namibia',
        'Nauru',
        'Nepal',
        'Netherlands',
        'New Zealand',
        'Nicaragua',
        'Niger',
        'Nigeria',
        'North Korea',
        'North Macedonia',
        'Norway',
        'Oman',
        'Pakistan',
        'Palau',
        'Palestine State',
        'Panama',
        'Papua New Guinea',
        'Paraguay',
        'Peru',
        'Philippines',
        'Poland',
        'Portugal',
        'Qatar',
        'Romania',
        'Russia',
        'Rwanda',
        'Saint Kitts and Nevis',
        'Saint Lucia',
        'Saint Vincent and the Grenadines',
        'Samoa',
        'San Marino',
        'Sao Tome and Principe',
        'Saudi Arabia',
        'Senegal',
        'Serbia',
        'Seychelles',
        'Sierra Leone',
        'Singapore',
        'Slovakia',
        'Slovenia',
        'Solomon Islands',
        'Somalia',
        'South Africa',
        'South Korea',
        'South Sudan',
        'Spain',
        'Sri Lanka',
        'Sudan',
        'Suriname',
        'Sweden',
        'Switzerland',
        'Syria',
        'Tajikistan',
        'Tanzania',
        'Thailand',
        'Timor-Leste',
        'Togo',
        'Tonga',
        'Trinidad and Tobago',
        'Tunisia',
        'Turkey',
        'Turkmenistan',
        'Tuvalu',
        'Uganda',
        'Ukraine',
        'United Arab Emirates',
        'United Kingdom',
        'United States',
        'Uruguay',
        'Uzbekistan',
        'Vanuatu',
        'Venezuela',
        'Vietnam',
        'Yemen',
        'Zambia',
        'Zimbabwe',
        'Other'
    ],


'State' => [
    // A — selected set with detailed coverage for major countries
    'Afghanistan' => ['Kabul Province', 'Kandahar Province', 'Herat Province', 'Nangarhar Province', 'Balkh Province', 'Kunar Province', 'Badakhshan Province', 'Bamyan Province'],
    'Albania' => ['Tirana County', 'Durrës County', 'Fier County', 'Shkodër County', 'Vlorë County', 'Elbasan County', 'Korçë County'],
    'Algeria' => ['Algiers', 'Oran', 'Constantine', 'Annaba', 'Batna', 'Sétif', 'Tizi Ouzou'],
    'Australia' => ['New South Wales', 'Victoria', 'Queensland', 'Western Australia', 'South Australia', 'Tasmania', 'Northern Territory', 'Australian Capital Territory'],
    'Austria' => ['Vienna', 'Lower Austria', 'Upper Austria', 'Styria', 'Tyrol', 'Carinthia', 'Salzburg', 'Vorarlberg'],
    'Azerbaijan' => ['Baku', 'Ganja', 'Sumqayit', 'Mingachevir', 'Lankaran', 'Sheki', 'Yevlakh'],

    // B
    'Bahamas' => ['New Providence', 'Grand Bahama', 'Abaco', 'Exuma', 'Long Island', 'Andros', 'Eleuthera'],
    'Bahrain' => ['Capital Governorate', 'Northern Governorate', 'Southern Governorate', 'Muharraq Governorate', 'Arabian Gulf Governorate'],
    'Bangladesh' => ['Dhaka Division', 'Chittagong Division', 'Khulna Division', 'Rajshahi Division', 'Barisal Division', 'Sylhet Division', 'Rangpur Division'],
    'Belarus' => ['Minsk Region', 'Brest Region', 'Gomel Region', 'Grodno Region', 'Mogilev Region', 'Vitebsk Region'],
    'Belgium' => ['Flanders', 'Wallonia', 'Brussels-Capital Region', 'Antwerp', 'East Flanders', 'West Flanders', 'Limburg'],
    'Belize' => ['Belize District', 'Cayo District', 'Orange Walk', 'Corozal', 'Stann Creek', 'Toledo'],
    'Benin' => ['Alibori', 'Atacora', 'Atlantique', 'Borgou', 'Collines', 'Donga', 'Littoral'],

    // C
    'Cambodia' => ['Phnom Penh', 'Kandal', 'Battambang', 'Siem Reap', 'Prey Veng', 'Banteay Meanchey', 'Kampong Cham'],
    'Cameroon' => ['Centre', 'Littoral', 'West', 'North-West', 'South-West', 'East', 'Adamawa'],
    'Canada' => ['Ontario', 'Quebec', 'British Columbia', 'Alberta', 'Manitoba', 'Saskatchewan', 'Nova Scotia', 'New Brunswick', 'Newfoundland and Labrador', 'Prince Edward Island', 'Northwest Territories', 'Yukon', 'Nunavut'],
    'China' => ['Beijing', 'Shanghai', 'Tianjin', 'Chongqing', 'Guangdong', 'Shandong', 'Jiangsu', 'Zhejiang', 'Sichuan', 'Henan'],
    'Colombia' => ['Bogotá (DC)', 'Antioquia', 'Valle del Cauca', 'Cundinamarca', 'Atlántico', 'Bolívar', 'Santander'],
    'Costa Rica' => ['San José', 'Alajuela', 'Cartago', 'Heredia', 'Guanacaste', 'Puntarenas', 'Limón'],
    'Croatia' => ['Zagreb', 'Split-Dalmatia', 'Istria', 'Osijek-Baranja', 'Primorje-Gorski Kotar', 'Zadar', 'Šibenik-Knin'],

    // D
    'Denmark' => ['Capital Region', 'Central Denmark Region', 'North Denmark Region', 'Region Zealand', 'Region of Southern Denmark'],
    'Djibouti' => ['Djibouti Region', 'Obock', 'Ali Sabieh', 'Dikhil', 'Tadjourah'],
    'Dominican Republic' => ['Distrito Nacional', 'Santo Domingo Province', 'Santiago', 'La Vega', 'San Cristóbal', 'Puerto Plata', 'San Pedro de Macorís'],

    // E
    'Ecuador' => ['Pichincha', 'Guayas', 'Manabí', 'Azuay', 'Loja', 'El Oro', 'Tungurahua'],
    'Egypt' => ['Cairo Governorate', 'Giza Governorate', 'Alexandria', 'Dakahlia', 'Sharqia', 'Gharbia', 'Fayoum'],
    'El Salvador' => ['San Salvador', 'La Libertad', 'Santa Ana', 'San Miguel', 'Chalatenango', 'La Union', 'Sonsonate'],
    'Estonia' => ['Harju County', 'Tartu County', 'Ida-Viru County', 'Pärnu County', 'Lääne-Viru County', 'Võru County', 'Viljandi County'],
    'Ethiopia' => ['Addis Ababa', 'Oromia', 'Amhara', 'Southern Nations', 'Tigray', 'Afar', 'Somali Region'],

    // F
    'Fiji' => ['Central Division', 'Western Division', 'Northern Division', 'Eastern Division', 'Rotuma'],
    'Finland' => ['Uusimaa', 'Pirkanmaa', 'South Ostrobothnia', 'Varsinais-Suomi', 'North Ostrobothnia', 'Lapland', 'Tavastia Proper'],
    'France' => ['Île-de-France', 'Provence-Alpes-Côte d\'Azur', 'Auvergne-Rhône-Alpes', 'Nouvelle-Aquitaine', 'Occitanie', 'Hauts-de-France', 'Grand Est', 'Brittany'],

    // G
    'Gabon' => ['Estuaire', 'Haut-Ogooué', 'Moyen-Ogooué', 'Ngounié', 'Ogooué-Ivindo', 'Woleu-Ntem', 'Ogooué-Lolo'],
    'Gambia' => ['Banjul', 'Kerewan', 'Kanifing', 'Brikama', 'Kuntaur', 'Mansakonko'],
    'Georgia' => ['Tbilisi', 'Kakheti', 'Kvemo Kartli', 'Imereti', 'Samegrelo-Zemo Svaneti', 'Guria', 'Adjara'],
    'Germany' => ['Bavaria', 'Berlin', 'Hamburg', 'North Rhine-Westphalia', 'Baden-Württemberg', 'Hesse', 'Saxony', 'Rhineland-Palatinate'],
    'Ghana' => ['Greater Accra', 'Ashanti', 'Western Region', 'Central', 'Eastern Region', 'Northern', 'Volta'],
    'Greece' => ['Attica', 'Central Macedonia', 'Crete', 'Peloponnese', 'Thessaly', 'Epirus', 'Ionian Islands'],

    // H
    'Honduras' => ['Francisco Morazán', 'Cortés', 'Atlántida', 'Santa Bárbara', 'Yoro', 'Colón', 'Copán'],
    'Hungary' => ['Budapest', 'Pest', 'Győr-Moson-Sopron', 'Vas', 'Veszprém', 'Baranya', 'Borsod-Abaúj-Zemplén'],

    // I
    'Iceland' => ['Capital Region', 'Southern Peninsula', 'Southern Region', 'Westfjords', 'Northwestern Region', 'Northeastern Region', 'Eastern Region'],
    'India' => ['Uttar Pradesh', 'Maharashtra', 'Bihar', 'West Bengal', 'Madhya Pradesh', 'Tamil Nadu', 'Rajasthan', 'Karnataka', 'Gujarat', 'Kerala'],
    'Indonesia' => ['Jakarta', 'West Java', 'Central Java', 'East Java', 'Banten', 'North Sumatra', 'South Sulawesi', 'Yogyakarta'],
    'Iran' => ['Tehran Province', 'Isfahan Province', 'Fars Province', 'Khorasan Razavi', 'East Azerbaijan', 'West Azerbaijan', 'Mazandaran'],
    'Iraq' => ['Baghdad Governorate', 'Basra Governorate', 'Nineveh', 'Erbil Governorate', 'Dhi Qar', 'Diyala', 'Kirkuk'],
    'Ireland' => ['Leinster', 'Munster', 'Connacht', 'Ulster', 'Dublin', 'Cork', 'Galway'],
    'Israel' => ['Central District', 'Tel Aviv District', 'Haifa District', 'Jerusalem District', 'Northern District', 'Southern District', 'Judea and Samaria (Areas)'],

    // J
    'Japan' => ['Tokyo Metropolis', 'Osaka Prefecture', 'Kanagawa Prefecture', 'Aichi Prefecture', 'Saitama Prefecture', 'Chiba Prefecture', 'Hokkaido', 'Hyōgo Prefecture'],
    'Jordan' => ['Amman Governorate', 'Irbid Governorate', 'Zarqa', 'Balqa', 'Aqaba', 'Mafraq', 'Karak'],

    // K
    'Kazakhstan' => ['Almaty Region', 'Akmola Region', 'East Kazakhstan', 'North Kazakhstan', 'Pavlodar', 'Karaganda', 'Atyrau'],
    'Kenya' => ['Nairobi County', 'Mombasa County', 'Kisumu County', 'Nakuru County', 'Kakamega', 'Uasin Gishu', 'Meru'],
    'Kuwait' => ['Al Asimah (Capital)', 'Hawalli', 'Al Ahmadi', 'Mubarak Al-Kabeer', 'Al Farwaniyah', 'Jahra'],
    'Kyrgyzstan' => ['Bishkek', 'Osh', 'Jalal-Abad', 'Batken', 'Issyk-Kul', 'Naryn', 'Talas'],

    // L
    'Laos' => ['Vientiane', 'Luang Prabang', 'Champasak', 'Savannakhet', 'Oudomxay', 'Bokeo', 'Khammouane'],
    'Latvia' => ['Riga', 'Vidzeme', 'Latgale', 'Kurzeme', 'Zemgale'],
    'Lebanon' => ['Beirut Governorate', 'Mount Lebanon', 'North Governorate', 'South Governorate', 'Beqaa', 'Nabatieh'],
    'Libya' => ['Tripolitania', 'Cyrenaica', 'Fezzan', 'Murzuq', 'Benghazi', 'Misrata', 'Jabal al Akhdar'],
    'Lithuania' => ['Vilnius County', 'Kaunas County', 'Klaipėda County', 'Šiauliai County', 'Panevėžys County'],

    // M
    'Malaysia' => ['Kuala Lumpur', 'Selangor', 'Johor', 'Penang', 'Perak', 'Sabah', 'Sarawak', 'Negeri Sembilan'],
    'Maldives' => ['Malé', 'Kaafu Atoll', 'Alifu Alifu Atoll', 'Baa Atoll', 'Lhaviyani Atoll', 'Noonu Atoll'],
    'Mali' => ['Bamako', 'Kayes Region', 'Koulikoro', 'Sikasso', 'Ségou', 'Mopti', 'Gao'],
    'Malta' => ['Northern Harbour', 'Southern Harbour', 'Gozo', 'Central Region', 'Western Region'],
    'Mexico' => ['Mexico City (CDMX)', 'Jalisco', 'Puebla', 'Guanajuato', 'Nuevo León', 'Chihuahua', 'Veracruz', 'Oaxaca'],
    'Micronesia' => ['Kosrae', 'Pohnpei', 'Chuuk', 'Yap'],
    'Moldova' => ['Chisinau', 'Cahul', 'Bălți', 'Tighina', 'Soroca', 'Orhei', 'Ungheni'],
    'Monaco' => ['Monaco'],
    'Mongolia' => ['Ulaanbaatar', 'Orkhon', 'Selenge', 'Darkhan-Uul', 'Töv Province', 'Khovd', 'Övörkhangai'],
    'Montenegro' => ['Podgorica', 'Nikšić', 'Herceg Novi', 'Bar', 'Bijelo Polje', 'Pljevlja', 'Berane'],

    // N
    'Netherlands' => ['North Holland', 'South Holland', 'Utrecht', 'North Brabant', 'Gelderland', 'Overijssel', 'Flevoland', 'Limburg'],
    'New Zealand' => ['Auckland', 'Wellington', 'Canterbury', 'Otago', 'Waikato', 'Bay of Plenty', 'Manawatū-Whanganui'],
    'Nigeria' => ['Lagos', 'Kano', 'Rivers', 'Oyo', 'Katsina', 'Kaduna', 'Anambra', 'Bauchi'],
    'North Korea' => ['Pyongyang', 'Rason', 'North Hamgyong', 'South Hamgyong', 'North Pyongan', 'South Pyongan', 'Kangwon'],
    'North Macedonia' => ['Skopje', 'Bitola', 'Kumanovo', 'Ohrid', 'Tetovo', 'Prilep', 'Kavadarci'],
    'Norway' => ['Oslo', 'Viken', 'Vestland', 'Trøndelag', 'Rogaland', 'Innlandet', 'Troms og Finnmark'],

    // O
    'Oman' => ['Muscat Governorate', 'Dhofar Governorate', 'North Al Batinah', 'South Al Batinah', 'Al Wusta', 'Al Sharqiyah North', 'Al Sharqiyah South'],

    // P
    'Pakistan' => ['Punjab', 'Sindh', 'Khyber Pakhtunkhwa', 'Balochistan', 'Islamabad Capital Territory', 'Gilgit-Baltistan', 'Azad Jammu and Kashmir'],
    'Panama' => ['Panamá', 'Colón', 'Chiriquí', 'Veraguas', 'Coclé', 'Los Santos', 'Herrera'],
    'Papua New Guinea' => ['National Capital District', 'Central Province', 'Morobe', 'Eastern Highlands', 'Western Highlands', 'Enga', 'Madang'],
    'Paraguay' => ['Central Department', 'Asunción', 'Alto Paraná', 'Concepción', 'Guairá', 'Itapúa', 'Caaguazú'],
    'Peru' => ['Lima Region', 'Cusco', 'Arequipa', 'La Libertad', 'Piura', 'Junín', 'Puno'],
    'Philippines' => ['National Capital Region (NCR)', 'Calabarzon', 'Central Luzon', 'Western Visayas', 'Central Visayas', 'Davao Region', 'Ilocos Region'],
    'Poland' => ['Masovian Voivodeship', 'Lesser Poland', 'Silesian', 'Greater Poland', 'Łódź', 'Pomeranian', 'Lower Silesian'],

    // Q
    'Qatar' => ['Doha Municipality', 'Al Rayyan', 'Al Wakrah', 'Al Khor', 'Umm Salal', 'Al Shamal', 'Al Shahaniya'],

    // R
    'Romania' => ['Bucharest', 'Cluj', 'Timiș', 'Iași', 'Constanța', 'Brașov', 'Galați'],
    'Russia' => ['Moscow (federal city)', 'Saint Petersburg (federal city)', 'Moscow Oblast', 'Krasnodar Krai', 'Tatarstan Republic', 'Sverdlovsk Oblast', 'Chelyabinsk Oblast', 'Novosibirsk Oblast'],
    'Rwanda' => ['Kigali', 'Northern', 'Southern', 'Eastern', 'Western'],

    // S
    'Saudi Arabia' => ['Riyadh Region', 'Makkah Region', 'Eastern Province', 'Medina Region', 'Asir Region', 'Tabuk Region', 'Al Jawf', 'Jazan'],
    'Senegal' => ['Dakar', 'Thiès', 'Diourbel', 'Saint-Louis', 'Ziguinchor', 'Kaolack', 'Sédhiou'],
    'Serbia' => ['Belgrade', 'Vojvodina', 'Šumadija and Western Serbia', 'Southern and Eastern Serbia', 'Raška'],
    'Seychelles' => ['Greater Victoria', 'Inner Islands', 'Outer Islands'],
    'Sierra Leone' => ['Western Area', 'Northern Province', 'Southern Province', 'Eastern Province'],
    'Singapore' => ['Central Region', 'East Region', 'North Region', 'North-East Region', 'West Region'],
    'Slovakia' => ['Bratislava Region', 'Trnava Region', 'Trenčín Region', 'Nitra Region', 'Žilina Region', 'Banská Bystrica', 'Prešov Region'],
    'Slovenia' => ['Ljubljana', 'Maribor', 'Kranj', 'Koper', 'Celje', 'Novo Mesto'],
    'South Africa' => ['Gauteng', 'Western Cape', 'KwaZulu-Natal', 'Eastern Cape', 'Limpopo', 'Mpumalanga', 'North West'],
    'South Korea' => ['Seoul', 'Busan', 'Incheon', 'Daegu', 'Daejeon', 'Gwangju', 'Gyeonggi-do'],
    'South Sudan' => ['Central Equatoria', 'Western Equatoria', 'Eastern Equatoria', 'Jonglei', 'Upper Nile', 'Unity', 'Lakes'],

    // T
    'Spain' => ['Andalusia', 'Catalonia', 'Community of Madrid', 'Valencian Community', 'Galicia', 'Basque Country', 'Castile and León'],
    'Sri Lanka' => ['Western Province', 'Central Province', 'Southern Province', 'Northern Province', 'Eastern Province', 'North Western Province', 'Uva Province'],
    'Sudan' => ['Khartoum', 'Darfur', 'Northern State', 'Blue Nile', 'Gedaref', 'Sennar', 'White Nile'],
    'Suriname' => ['Paramaribo', 'Wanica', 'Nickerie', 'Commewijne', 'Saramacca', 'Coronie', 'Marowijne'],
    'Sweden' => ['Stockholm County', 'Västra Götaland', 'Skåne County', 'Uppsala County', 'Västmanland', 'Östergötland', 'Jönköping'],
    'Switzerland' => ['Zurich', 'Bern', 'Vaud', 'Geneva', 'Basel-Stadt', 'Aargau', 'St. Gallen'],
    'Syria' => ['Damascus', 'Aleppo', 'Homs', 'Latakia', 'Hama', 'Deir ez-Zor', 'Raqqa'],
    'Taiwan' => ['Taipei', 'New Taipei', 'Taichung', 'Tainan', 'Kaohsiung', 'Taoyuan', 'Hsinchu'],
    'Tajikistan' => ['Sughd', 'Khatlon', 'Districts of Republican Subordination', 'Gorno-Badakhshan'],
    'Tanzania' => ['Dar es Salaam', 'Mwanza', 'Arusha', 'Mbeya', 'Kilimanjaro', 'Morogoro', 'Dodoma'],
    'Thailand' => ['Bangkok', 'Chiang Mai', 'Chonburi', 'Phuket', 'Nakhon Ratchasima', 'Khon Kaen', 'Songkhla'],
    'Timor-Leste' => ['Dili', 'Baucau', 'Liquiçá', 'Manatuto', 'Viqueque', 'Ermera', 'Bobonaro'],
    'Togo' => ['Lomé', 'Savanes', 'Centrale', 'Kara', 'Plateaux', 'Maritime'],
    'Tonga' => ['Tongatapu', 'Vavaʻu', 'Haʻapai', 'ʻEua', 'Niuas'],
    'Turkey' => ['Istanbul', 'Ankara', 'Izmir', 'Antalya', 'Bursa', 'Adana', 'Mersin', 'Konya'],
    'Turkmenistan' => ['Ahal', 'Balkan', 'Dashoguz', 'Lebap', 'Mary'],

    // U
    'Uganda' => ['Central Region', 'Western Region', 'Eastern Region', 'Northern Region', 'Kampala', 'Lango', 'Teso'],
    'Ukraine' => ['Kyiv', 'Kharkiv Oblast', 'Odessa Oblast', 'Dnipropetrovsk Oblast', 'Lviv Oblast', 'Donetsk (partially occupied)', 'Zaporizhzhia'],
    'United Arab Emirates' => ['Abu Dhabi', 'Dubai', 'Sharjah', 'Ajman', 'Umm Al-Quwain', 'Ras Al Khaimah', 'Fujairah'],
    'United Kingdom' => ['England', 'Scotland', 'Wales', 'Northern Ireland', 'Greater London', 'West Midlands', 'Greater Manchester'],
    'United States' => ['Alabama','Alaska','Arizona','Arkansas','California','Colorado','Connecticut','Delaware','Florida','Georgia','Hawaii','Idaho','Illinois','Indiana','Iowa','Kansas','Kentucky','Louisiana','Maine','Maryland','Massachusetts','Michigan','Minnesota','Mississippi','Missouri','Montana','Nebraska','Nevada','New Hampshire','New Jersey','New Mexico','New York','North Carolina','North Dakota','Ohio','Oklahoma','Oregon','Pennsylvania','Rhode Island','South Carolina','South Dakota','Tennessee','Texas','Utah','Vermont','Virginia','Washington','West Virginia','Wisconsin','Wyoming'],

    // V, W, Y, Z
    'Venezuela' => ['Caracas', 'Zulia', 'Miranda', 'Carabobo', 'Anzoátegui', 'Barinas', 'Aragua'],
    'Vietnam' => ['Hanoi', 'Ho Chi Minh City', 'Da Nang', 'Binh Duong', 'Hai Phong', 'Can Tho', 'Thanh Hoa'],
    'Yemen' => ['Sana\'a', 'Aden', 'Taiz', 'Hadhramaut', 'Al Hudaydah', 'Ibb', 'Amran'],
    'Zambia' => ['Lusaka', 'Copperbelt', 'Southern Province', 'Northern Province', 'Central Province', 'Eastern Province', 'Luapula'],
    'Zimbabwe' => ['Harare', 'Bulawayo', 'Manicaland', 'Mashonaland Central', 'Mashonaland East', 'Masvingo', 'Matabeleland North', 'Matabeleland South'],
],


    'City' => [
        'Herat Province' => ['Herat'],
        'Kabul Province' => ['Kabul'],

        'New South Wales' => ['Sydney'],
        'Victoria' => ['Melbourne'],

        'Rio de Janeiro State' => ['Rio de Janeiro'],
        'São Paulo State' => ['São Paulo'],

        'British Columbia' => ['Vancouver'],
        'Ontario' => ['Toronto', 'Ottawa'],

        'Beijing' => ['Beijing city'],
        'Guangdong' => ['Guangzhou', 'Shenzhen'],
        'Shanghai' => ['Shanghai city'],

        'Île‑de‑France' => ['Paris'],
        'Provence-Alpes-Côte d’Azur' => ['Marseille', 'Nice'],

        'Bavaria' => ['Munich'],
        'Berlin (state)' => ['Berlin'],

        'Delhi' => ['New Delhi', 'South Delhi'],
        'Karnataka' => ['Bengaluru', 'Mysore'],
        'Maharashtra' => ['Mumbai', 'Pune'],

        'Fars Province (Shiraz)' => ['Shiraz'],
        'Isfahan Province' => ['Isfahan'],
        'Tehran Province' => ['Tehran'],

        'Baghdad Governorate' => ['Baghdad'],
        'Basra Governorate' => ['Basra'],

        'Lazio' => ['Rome'],
        'Lombardy' => ['Milan'],

        'Osaka Prefecture' => ['Osaka'],
        'Tokyo Metropolis' => ['Tokyo'],

        'Kuala Lumpur Territory' => ['Kuala Lumpur'],
        'Selangor' => ['Shah Alam'],

        'Mexico City (CDMX)' => ['Mexico City'],
        'Quintana Roo' => ['Cancún'],

        'North Holland' => ['Amsterdam'],
        'South Holland' => ['Rotterdam'],

        'Oslo County' => ['Oslo'],
        'Vestland County' => ['Bergen'],

        'Muscat Governorate' => ['Muscat'],

        'Balochistan' => ['Quetta'],
        'Khyber Pakhtunkhwa' => ['Peshawar', 'Mardan', 'Abbottabad'],
        'Punjab' => ['Lahore', 'Faisalabad', 'Rawalpindi', 'Multan'],
        'Sindh' => ['Karachi', 'Hyderabad', 'Sukkur'],

        'Doha Municipality' => ['Doha'],

        'Moscow (federal city)' => ['Moscow'],
        'Saint Petersburg (federal city)' => ['Saint Petersburg'],
        'Tatarstan Republic' => ['Kazan'],

        'Mecca Region' => ['Mecca'],
        'Riyadh Region' => ['Riyadh'],

        'Gauteng Province' => ['Johannesburg', 'Pretoria'],
        'Western Cape' => ['Cape Town'],

        'Catalonia' => ['Barcelona'],
        'Community of Madrid' => ['Madrid'],

        'Antalya Province' => ['Antalya'],
        'Istanbul Province' => ['Istanbul'],

        // United Arab Emirates (UAE)
        'Abu Dhabi Emirate' => ['Abu Dhabi'],
        'Dubai Emirate' => ['Dubai'],
        'Sharjah Emirate' => ['Sharjah'],
        'Ajman Emirate' => ['Ajman'],
        'Umm Al-Quwain Emirate' => ['Umm Al-Quwain'],
        'Ras Al Khaimah Emirate' => ['Ras Al Khaimah'],
        'Fujairah Emirate' => ['Fujairah'],

        'England' => ['London', 'Manchester'],
        'Scotland' => ['Edinburgh', 'Glasgow'],

        'California' => ['Los Angeles', 'San Francisco'],
        'New York' => ['New York City', 'Buffalo'],
        'Texas' => ['Houston', 'Dallas']
    ],
];
