<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class SysUserType30OnboardQuestionsAnswers extends Model
{
    use HasFactory;

    protected $table = 'sys_user_type_30_onboard_questions_answers';
    protected $primaryKey = 'ID';
    public $timestamps = false;

    protected $fillable = [
        'PatientUserID',
        'SessionZegoCloudConnectID',
        'QuestionCompletionStatus',
        'Id1_Answer_text',
        'Id1_AnswerOptionNumber',
        'Id2_Answer_text',
        'Id2_AnswerOptionNumber',
        'Id3_Answer_text',
        'Id3_AnswerOptionNumber',
        'Id4_Answer_text',
        'Id4_AnswerOptionNumber',
        'Id5_Answer_text',
        'Id5_AnswerOptionNumber',
        'Id6_Answer_text',
        'Id6_AnswerOptionNumber',
        'Id7_Answer_text',
        'Id7_AnswerOptionNumber',
        'Id8_Answer_text',
        'Id8_AnswerOptionNumber',
        'Id9_Answer_text',
        'Id9_AnswerOptionNumber',
        'Id10_Answer_text',
        'Id10_AnswerOptionNumber',
        'Id11_Answer_text',
        'Id11_AnswerOptionNumber',
        'Id12_Answer_text',
        'Id12_AnswerOptionNumber',
        'Id13_Answer_text',
        'Id13_AnswerOptionNumber',
        'Id14_Answer_text',
        'Id14_AnswerOptionNumber',
        'Id15_Answer_text',
        'Id15_AnswerOptionNumber',
        'Id16_Answer_text',
        'Id16_AnswerOptionNumber',
        'Id17_Answer_text',
        'Id17_AnswerOptionNumber',
        'Id18_Answer_text',
        'Id18_AnswerOptionNumber',
        'Id19_Answer_text',
        'Id19_AnswerOptionNumber',
        'Id20_Answer_text',
        'Id20_AnswerOptionNumber',
        'Id21_Answer_text',
        'Id21_AnswerOptionNumber',
        'Id22_Answer_text',
        'Id22_AnswerOptionNumber',
        'Id23_Answer_text',
        'Id23_AnswerOptionNumber',
        'Id24_Answer_text',
        'Id24_AnswerOptionNumber',
        'Id25_Answer_text',
        'Id25_AnswerOptionNumber',
        'Id26_Answer_text',
        'Id26_AnswerOptionNumber',
        'Id27_Answer_text',
        'Id27_AnswerOptionNumber',
        'Id28_Answer_text',
        'Id28_AnswerOptionNumber',
        'Id29_Answer_text',
        'Id29_AnswerOptionNumber',
        'Id30_Answer_text',
        'Id30_AnswerOptionNumber',
        'Id31_Answer_text',
        'Id31_AnswerOptionNumber',
        'Id32_Answer_text',
        'Id32_AnswerOptionNumber',
        'Id33_Answer_text',
        'Id33_AnswerOptionNumber',
        'Id34_Answer_text',
        'Id34_AnswerOptionNumber',
        'Id35_Answer_text',
        'Id35_AnswerOptionNumber',
        'Id36_Answer_text',
        'Id36_AnswerOptionNumber',
        'Id37_Answer_text',
        'Id37_AnswerOptionNumber',
        'Id38_Answer_text',
        'Id38_AnswerOptionNumber',
        'Id39_Answer_text',
        'Id39_AnswerOptionNumber',
    ];
}
